# web server
server:
  port: 9081
  servlet:
    context-path: /hello/boot

# spring auto configure
spring:
  application:
    name: hello-boot


# logging
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
    com.example.learn.spring.boot.openfeign.hello: debug

# open-feign

feign:
  client:
    config:
      default:
        loggerLevel: FULL  #日志中http报文是否展示全部

mock-service:
  url: http://localhost:9080/mock