# web server
server:
  port: 9081
  servlet:
    context-path: /hello/boot

# spring auto configure
spring:
  application:
    name: hello-boot


# logging
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
    feign.Client: DEBUG
    feign.Logger: DEBUG
    feign.Request: DEBUG
    feign.Response: DEBUG
    com.example.learn.spring.boot.openfeign.hello: DEBUG

# open-feign

feign:
  client:
    config:
      default:
        loggerLevel: FULL

mock-service:
  url: http://localhost:9080/mock